name: Clean NestJs App after merge closed
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "**/*.ts"
      - "**/*.js"
      - "package.json"
      - "package.lock.json"
      - "Dockerfile"
      - ".github/workflows/development.yml"
      - ".github/workflows/clean.yml"
    types: [closed]

env:
  REGISTRY: ${{ secrets.OGTIC_DOCKER_REGISTRY }}
  
jobs:    
  delete-image:
    name: Delete App Image from registry
    runs-on: ubuntu-20.04
    env:
      DIGEST_FILE: digest_header_file
    outputs:
      image_tag: ${{ steps.image_info.outputs.image_tag }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Set Image Info name
        id: image_info
        run: |
          echo "image_name=${{ env.REGISTRY }}/ogtic/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}" >> $GITHUB_OUTPUT
          echo "image_tag=$(echo "${{ env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}" | sha256sum | cut -c 1-5)" >> $GITHUB_OUTPUT
      
      - name: Delete image from registry
        run: |
          touch $DIGEST_FILE
          curl \
            -u ${{ secrets.OGTIC_DOCKER_REGISTRY_USERNAME }}:${{ secrets.OGTIC_DOCKER_REGISTRY_PASSWORD }} \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            -X HEAD https://${{ env.REGISTRY }}/v2/ogtic/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/manifests/${{ steps.image_info.outputs.image_tag }} \
            -sI |  tr -d '\r' | sed -En "s/^docker-content-digest: (.*)/\1/p" > $DIGEST_FILE
          curl \
            -u ${{ secrets.OGTIC_DOCKER_REGISTRY_USERNAME }}:${{ secrets.OGTIC_DOCKER_REGISTRY_PASSWORD }} \
            -X DELETE https://${{ env.REGISTRY }}/v2/ogtic/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/manifests/$(cat $DIGEST_FILE)


  remove-deploy-k8s:
    name: Removes deploy on K8s cluster
    env:
      NAMESPACE: reuniones-ogtic-dev
    needs: [ delete-image ]
    runs-on: [self-hosted, pys-k8s-arc]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1
        
      - name: Install Kubectl and Helm v3 
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubectl
            helm
          kubectl: '1.25.4'
          helm: '3.11.1'

      - name: Create Kubeconfig File
        run: |
          mkdir ~/.kube
          echo '${{ secrets.KUBECONFIG }}' > ~/.kube/config

      - name: Uninstall Helm Release
        run: |
          helm uninstall ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}-${{ needs.delete-image.outputs.image_tag }} \
          --namespace ${{ env.NAMESPACE }} \
          --wait

      - name: Remove secrets
        run: |
          kubectl --namespace ${{ env.NAMESPACE }} delete secret \
            ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}-${{ needs.delete-image.outputs.image_tag }} \
            --ignore-not-found
